#!/usr/bin/env ruby
ARGV[0] = 'describe' if ARGV[0] == 'get'
command = if !ARGV.select {|i| i == 'help' }.empty?
  "#{ARGV[1]}#{ARGV[2] == 'help' ? '' : " #{ARGV[0]}-#{ARGV[2]}"} help"
else
  "#{ARGV[1]} #{ARGV[0]}-#{ARGV[2]} #{ARGV[3..-1].join(' ')} --output table"
end
puts `aws #{command}`
